# Makefile

# Target padrão
all: verificar

# Target 1: compila o programa em C
compilar:
	gcc arquivo_c.c -o arquivo_c

# Target 2: roda o programa
executar:
	./arquivo_c

# Target 3: roda dois comandos Linux
verificar:
	ls -l
	wc -l arquivo_c.c

# Target 4: remove o executável
clean:
	rm -f arquivo_c

